### ISSUE TITLE
Add Checks in cronJobs.js

### ISSUE THREAD

**Issue by uzair-ali10** [integrateme-co/integrate-io#16]
In `services/cronjobs.js` add checks to verify if `records` is empty or not

**Comment by brijeshshah13** [comment]
@uzair-ali10 please assign this to me

**Comment by uzair-ali10** [comment]
> @uzair-ali10 please assign this to me

This one is scrapped as we are planning to completely re-write or remove this feature

**Comment by brijeshshah13** [comment]
i see. then can we close this one and maybe create a new one later

**Comment by uzair-ali10** [comment]
> i see. then can we close this one and maybe create a new one later

Yes Closing this one now
